[tool.poetry]
name = "coarl-counterspeech"
version = "0.1.0"
description = ""
authors = ["AmeyHengle <ameyhengle22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
absl-py = "==2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
